name: noaa-oap
channels:
  - conda-forge
  - defaults
dependencies:
  - netcdf4=1.5.7
  - numpy=1.21.2
  - matplotlib=3.5.0
  - pandas=1.3.3
  - xarray=0.19.0
  - cartopy=0.18.0
  - cmocean=2.0
  - geographiclib=1.52
  - gsw=3.4.0
  - pip=21.0.1
  - pip:
    - pyco2sys==1.7.1
